---
- name: installing lamp server
  hosts: all
  become: yes
  tasks:
    - name: print os details
      ansible.builtin.debug:
        msg: "family: {{ ansible_facts['os_family'] }} distribution: {{ ansible_facts['distribution'] }}"
    
    - name: print ansible facts
      ansible.builtin.debug:
        var: ansible_facts['default_ipv4']

    - name: check if the playbook is being executed on supported os
      ansible.builtin.fail:
        msg: "This playbook is designed to work on ubuntu and redhat only"
      when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "RedHat"

    - name: installing apache
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present
    - name: debug apache installed
      ansible.builtin.debug:
        msg: "Installed apache server using package {{ package_name }}"
      

    - name: Enabling and starting apache
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        enabled: yes
        state: started
    - name: debug apache service started and enabled
      ansible.builtin.debug:
        msg: "Enabled and started apache"
      

    - name: installing PHP
      ansible.builtin.package:
        name: "{{ item }}"         
        state: present
      loop: "{{ php_packages }}"
      notify:
        - restart apache
    - name: debug php modules installed
      ansible.builtin.debug:
        msg: "Installed php-packages {{ php_packages }}"
      

    - name: copying info.php file
      ansible.builtin.copy:
        src: info.php
        dest: "{{ info_page_path }}"
      notify:
        - restart apache
    - name: debug info.php 
      ansible.builtin.debug:
        msg: "Created info.php at {{ info_page_path }}"
    
  handlers:
    - name: restart apache
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        state: restarted

    
      