---
java_package_Ubuntu: openjdk-11-jdk
java_home_ubuntu: /usr/lib/jvm/java-11-openjdk-amd64
group: tomcat
user: tomcat
shell: /bin/false
homedir: /opt/tomcat
tomcat_major_version: 10
tomcat_version: 10.1.9